name: easy_mvvm
description: An easy mvvm solution that includes ways to manage routes, views, viewmodels, and the mvvm architecture
version: 0.0.7
homepage: https://github.com/rjs580/easy_mvvm
repository: https://github.com/rjs580/easy_mvvm
issue_tracker: https://github.com/rjs580/easy_mvvm/issues
documentation: https://pub.dev/documentation/easy_mvvm/latest/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

executables:
  easy_mvvm:

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  recase: ^4.1.0
  meta: ^1.9.1
  get_it: ^7.6.0
  args: ^2.4.2
  pubspec_yaml: ^3.1.0
  colorize: ^3.0.0
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
