name: easy_mvvm
description: An easy mvvm solution that includes ways to manage routes, views, viewmodels, and the mvvm architecture
version: 0.0.3-1
homepage: https://github.com/rjs580/easy_mvvm
repository: https://github.com/rjs580/easy_mvvm
issue_tracker: https://github.com/rjs580/easy_mvvm/issues
documentation: https://pub.dev/documentation/easy_mvvm/latest/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  recase: ^4.1.0
  meta: ^1.8.0
  get_it: ^7.2.0
  args: ^2.4.0
  pubspec_yaml: ^3.1.0
  colorize: any
  code_builder: ^4.4.0
  dart_style: ^2.2.5

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
