name: easy_mvvm
description: Easiest way to use MVVM in your flutter application
version: 0.0.1
homepage: https://github.com/rjs580/easy_mvvm
repository: https://github.com/rjs580/easy_mvvm
issue_tracker: https://github.com/rjs580/easy_mvvm/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.3
  recase: ^4.0.0
  meta: ^1.7.0
  get_it: ^7.2.0
  args: ^2.3.1
  pubspec_yaml: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
